import { Match, Profile } from '../types';

export const MATCHES_DATA: Match[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    age: 26,
    place: 'Mumbai, Maharashtra',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    profession: 'Software Engineer',
    education: 'B.Tech, IIT Bombay',
    about: 'Passionate about technology and spirituality. Love reading, traveling, and exploring new cuisines. Looking for someone who shares similar values and has a good sense of humor.',
    height: "5'4\"",
    motherTongue: 'Hindi',
    caste: 'Brahmin',
    salary: '₹18-25 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '2',
    name: 'Ananya Reddy',
    age: 24,
    place: 'Hyderabad, Telangana',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    profession: 'Doctor',
    education: 'MBBS, AIIMS',
    about: 'Dedicated doctor who believes in serving humanity. Family-oriented with traditional values. Enjoy music, yoga, and spending quality time with loved ones.',
    height: "5'5\"",
    motherTongue: 'Telugu',
    caste: 'Reddy',
    salary: '₹12-18 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '3',
    name: 'Kavya Nair',
    age: 27,
    place: 'Kochi, Kerala',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    profession: 'Chartered Accountant',
    education: 'B.Com, Christ University',
    about: 'Finance professional with a creative side. Love classical dance (Bharatanatyam), cooking traditional Kerala dishes, and weekend getaways to hill stations.',
    height: "5'3\"",
    motherTongue: 'Malayalam',
    caste: 'Nair',
    salary: '₹15-20 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '4',
    name: 'Meera Patel',
    age: 25,
    place: 'Ahmedabad, Gujarat',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    profession: 'Architect',
    education: 'B.Arch, CEPT University',
    about: 'Creative soul who loves designing spaces that inspire. Vegetarian, spiritual, and believe in simple living. Passionate about sustainable architecture.',
    height: "5'6\"",
    motherTongue: 'Gujarati',
    caste: 'Patel',
    salary: '₹10-15 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '5',
    name: 'Divya Iyer',
    age: 28,
    place: 'Chennai, Tamil Nadu',
    photo: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    profession: 'Data Scientist',
    education: 'M.Tech, IIT Madras',
    about: 'Tech enthusiast with traditional values. Love Carnatic music, temple visits, and solving complex problems. Looking for an intellectually stimulating partner.',
    height: "5'4\"",
    motherTongue: 'Tamil',
    caste: 'Iyer',
    salary: '₹25-35 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '6',
    name: 'Sneha Kulkarni',
    age: 26,
    place: 'Pune, Maharashtra',
    photo: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    profession: 'Marketing Manager',
    education: 'MBA, Symbiosis',
    about: 'Outgoing personality with strong family values. Love hiking, photography, and exploring cafes. Looking for someone adventurous yet grounded.',
    height: "5'5\"",
    motherTongue: 'Marathi',
    caste: 'Brahmin',
    salary: '₹14-18 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '7',
    name: 'Riya Gupta',
    age: 25,
    place: 'Delhi, NCR',
    photo: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    profession: 'Fashion Designer',
    education: 'NIFT Delhi',
    about: 'Creative mind with an eye for aesthetics. Love art exhibitions, fashion weeks, and traveling to new places. Seeking a partner who appreciates creativity.',
    height: "5'7\"",
    motherTongue: 'Hindi',
    caste: 'Agarwal',
    salary: '₹12-16 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '8',
    name: 'Aishwarya Menon',
    age: 27,
    place: 'Bangalore, Karnataka',
    photo: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    profession: 'UX Designer',
    education: 'M.Des, NID',
    about: 'Design thinking enthusiast who loves creating user-friendly experiences. Enjoy reading, sketching, and weekend treks. Looking for a thoughtful companion.',
    height: "5'4\"",
    motherTongue: 'Malayalam',
    caste: 'Menon',
    salary: '₹20-28 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '9',
    name: 'Pooja Joshi',
    age: 24,
    place: 'Jaipur, Rajasthan',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    profession: 'Teacher',
    education: 'M.Ed, Rajasthan University',
    about: 'Passionate educator who loves shaping young minds. Enjoy classical music, painting, and cooking Rajasthani cuisine. Family-oriented with traditional values.',
    height: "5'3\"",
    motherTongue: 'Hindi',
    caste: 'Brahmin',
    salary: '₹6-8 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '10',
    name: 'Nisha Rao',
    age: 26,
    place: 'Mysore, Karnataka',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    profession: 'Lawyer',
    education: 'LLB, NLSIU Bangalore',
    about: 'Justice-driven professional with a compassionate heart. Love debates, reading legal thrillers, and yoga. Seeking an intellectually compatible partner.',
    height: "5'5\"",
    motherTongue: 'Kannada',
    caste: 'Rao',
    salary: '₹15-22 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '11',
    name: 'Tanvi Deshmukh',
    age: 28,
    place: 'Nagpur, Maharashtra',
    photo: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    profession: 'Civil Engineer',
    education: 'B.Tech, VNIT Nagpur',
    about: 'Building dreams into reality. Love traveling to historical places, reading about architecture, and playing badminton. Looking for a supportive life partner.',
    height: "5'6\"",
    motherTongue: 'Marathi',
    caste: 'Deshmukh',
    salary: '₹12-16 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '12',
    name: 'Shruti Agarwal',
    age: 25,
    place: 'Kolkata, West Bengal',
    photo: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    profession: 'Investment Banker',
    education: 'MBA, IIM Calcutta',
    about: 'Finance professional with a love for Bengali culture. Enjoy Rabindra Sangeet, durga puja celebrations, and exploring street food. Seeking an ambitious partner.',
    height: "5'4\"",
    motherTongue: 'Bengali',
    caste: 'Agarwal',
    salary: '₹30-40 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '13',
    name: 'Aditi Saxena',
    age: 27,
    place: 'Lucknow, Uttar Pradesh',
    photo: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    profession: 'Content Writer',
    education: 'MA English, BHU',
    about: 'Words are my passion. Love Urdu poetry, Lucknowi cuisine, and heritage walks. Looking for someone who appreciates literature and culture.',
    height: "5'3\"",
    motherTongue: 'Hindi',
    caste: 'Kayastha',
    salary: '₹8-12 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '14',
    name: 'Deepika Choudhary',
    age: 26,
    place: 'Chandigarh, Punjab',
    photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    profession: 'HR Manager',
    education: 'MBA HR, Punjab University',
    about: 'People person who loves building connections. Enjoy bhangra, road trips, and trying new restaurants. Seeking a fun-loving and caring partner.',
    height: "5'6\"",
    motherTongue: 'Punjabi',
    caste: 'Khatri',
    salary: '₹14-18 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
  {
    id: '15',
    name: 'Ishita Verma',
    age: 24,
    place: 'Indore, Madhya Pradesh',
    photo: 'https://images.unsplash.com/photo-1464863979621-258859e62245?w=800',
    introVideo: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    profession: 'Dentist',
    education: 'BDS, Government Dental College',
    about: 'Healthcare professional with a warm smile. Love cooking, gardening, and spending time with family. Looking for a kind-hearted life partner.',
    height: "5'4\"",
    motherTongue: 'Hindi',
    caste: 'Brahmin',
    salary: '₹10-14 LPA',
    workingStatus: 'Working',
    religion: 'Hindu',
    maritalStatus: 'Never Married',
  },
];

export const DEFAULT_USER_PROFILE: Profile = {
  id: 'user1',
  name: 'Rahul Kumar',
  age: 28,
  gender: 'Male',
  place: 'Bangalore, Karnataka',
  state: 'Karnataka',
  country: 'India',
  photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
  profession: 'Product Manager',
  company: 'Tech Company',
  education: 'MBA, IIM Bangalore',
  about: 'Spiritual, family-oriented person looking for a life partner who values relationships and personal growth.',
  height: 178,
  weight: 72,
  bodyType: 'Athletic',
  complexion: 'Wheatish',
  motherTongue: 'Hindi',
  caste: 'Kayastha',
  salary: 35,
  workingStatus: 'Working',
  religion: 'Hindu',
  maritalStatus: 'Never Married',
  familyType: 'Nuclear',
  familyStatus: 'Upper Middle Class',
  familyValues: 'Moderate',
  diet: 'Vegetarian',
  smoking: 'No',
  drinking: 'Occasionally',
};
